import os.path
import tensorflow as tf

# This model is generated by handdigit_classification_with_keras.py
model_path = os.path.dirname(os.path.abspath(__name__)) + '/deep_learning/saved_model/handdigit.keras'

converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quantized_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_quantized_model)


